In [1]:
import numpy as np

# 1. Define the Training Data (Inputs X and expected Outputs Y)
# X: 4 rows (training examples), 2 columns (features)
training_inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
# Y: 4 rows (expected output)
training_outputs = np.array([[0, 0, 0, 1]]).T # .T is for Transpose

# 2. Initialize Weights and Bias
# Two input features, one output neuron -> 2 weights
np.random.seed(1) # for consistent results
synaptic_weights = 2 * np.random.random((2, 1)) - 1 # Random weights between -1 and 1
bias = np.random.random((1, 1)) # Random bias

# 3. Activation Function: Sigmoid (squashes the value between 0 and 1)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of Sigmoid (used for Backpropagation)
def sigmoid_derivative(x):
    return x * (1 - x)

# 4. Training the Network
print("Initial Random Weights:\n", synaptic_weights)

for iteration in range(10000): # Train for 10,000 iterations

    # --- Forward Pass ---
    # a. Calculate Weighted Sum (Input * Weights + Bias)
    input_layer = training_inputs
    z = np.dot(input_layer, synaptic_weights) + bias

    # b. Get the Prediction (Output of the Sigmoid function)
    output = sigmoid(z)

    # --- Backpropagation ---
    # a. Calculate the Error (Expected - Actual)
    error = training_outputs - output

    # b. Calculate adjustments to the weights
    # This involves the error and the derivative of the activation function
    adjustments = np.dot(input_layer.T, error * sigmoid_derivative(output))

    # c. Update Weights (Learning Step)
    synaptic_weights += adjustments

    # (Note: Bias adjustment is simplified here for time)

# 5. Testing the Trained Network
print("\nWeights after Training:\n", synaptic_weights)

print("\nFinal Output (New Prediction):")
new_input = np.array([1, 0]) # A new example
final_output = sigmoid(np.dot(new_input, synaptic_weights) + bias)
print(f"Input: {new_input} -> Prediction: {final_output.round(2)}")

Initial Random Weights:
 [[-0.16595599]
 [ 0.44064899]]

Weights after Training:
 [[-7.62498782e-05]
 [-7.62498782e-05]]

Final Output (New Prediction):
Input: [1 0] -> Prediction: [[0.5]]


In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# -------------------------------------------------------
# 1. LOAD DATA
# -------------------------------------------------------

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

print("Dataset Loaded")
print("Original Training Shape:", X_train.shape)     # (60000, 28, 28)
print("Original Test Shape:", X_test.shape)

# -------------------------------------------------------
# 2. PREPROCESS DATA
# -------------------------------------------------------

# Add channel dimension (grayscale = 1 channel)
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1).astype("float32")
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1).astype("float32")

print("\nAfter Reshaping:")
print("Train Data Shape:", X_train.shape)   # (60000, 28, 28, 1)
print("Test Data Shape:", X_test.shape)

# Normalize
X_train /= 255.0
X_test /= 255.0

# Print a small sample batch (first 4 images)
print("\nSample Image Tensor Values (first 4 samples):")
print(X_train[:4])
print("Sample Labels:", y_train[:4])

# -------------------------------------------------------
# 3. BUILD THE MODEL
# -------------------------------------------------------

model = Sequential([
    Conv2D(32, (3, 3), activation="relu", input_shape=(28, 28, 1)),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    Dense(128, activation="relu"),
    Dense(10, activation="softmax")
])

print("\nModel Architecture Summary:")
model.summary()

# -------------------------------------------------------
# 4. COMPILE
# -------------------------------------------------------

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# -------------------------------------------------------
# 5. TRAINING
# -------------------------------------------------------

print("\n--- Starting Keras Model Training ---")
history = model.fit(
    X_train,
    y_train,
    epochs=3,
    batch_size=32,
    validation_data=(X_test, y_test)
)

# -------------------------------------------------------
# 6. EVALUATE
# -------------------------------------------------------

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)

print("\n--- Evaluation Complete ---")
print(f"Keras MNIST Test Loss: {loss:.4f}")
print(f"Keras MNIST Test Accuracy: {accuracy * 100:.2f}%")


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step
Dataset Loaded
Original Training Shape: (60000, 28, 28)
Original Test Shape: (10000, 28, 28)

After Reshaping:
Train Data Shape: (60000, 28, 28, 1)
Test Data Shape: (10000, 28, 28, 1)

Sample Image Tensor Values (first 4 samples):
[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]


/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 5408)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       692,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 693,962 (2.65 MB)

 Trainable params: 693,962 (2.65 MB)

 Non-trainable params: 0 (0.00 B)


--- Starting Keras Model Training ---
Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 48s 25ms/step - accuracy: 0.9108 - loss: 0.2995 - val_accuracy: 0.9785 - val_loss: 0.0647
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 46s 24ms/step - accuracy: 0.9848 - loss: 0.0508 - val_accuracy: 0.9818 - val_loss: 0.0554
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 45s 24ms/step - accuracy: 0.9906 - loss: 0.0306 - val_accuracy: 0.9833 - val_loss: 0.0495

--- Evaluation Complete ---
Keras MNIST Test Loss: 0.0495
Keras MNIST Test Accuracy: 98.33%


In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

# -------------------------------------------------------
# 1. PREPROCESS & LOAD DATA
# -------------------------------------------------------

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

trainset = torchvision.datasets.CIFAR10(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

trainloader = torch.utils.data.DataLoader(
    trainset, batch_size=4, shuffle=True, num_workers=0
)

print("Dataset Loaded:")
print("Total training samples:", len(trainset))
print("Batch size:", 4)
print("Image shape:", trainset[0][0].shape)   # (3, 32, 32)

# Print a small sample batch (tensor only)
sample_inputs, sample_labels = next(iter(trainloader))
print("\nSample batch - images tensor shape:", sample_inputs.shape)
print("Sample batch - labels:", sample_labels)

# -------------------------------------------------------
# 2. DEFINE MODEL
# -------------------------------------------------------
class SimpleCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = torch.flatten(x, 1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = SimpleCNN()
print("\nModel Architecture:")
print(net)

# -------------------------------------------------------
# 3. LOSS AND OPTIMIZER
# -------------------------------------------------------
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

# -------------------------------------------------------
# 4. TRAINING LOOP WITH PRINTS
# -------------------------------------------------------
print("\n--- Starting Training ---")

for epoch in range(2):
    running_loss = 0.0
    print(f"\nEpoch {epoch+1} ----------------------")

    for step, data in enumerate(trainloader, 0):
        inputs, labels = data

        optimizer.zero_grad()

        outputs = net(inputs)

        if step == 0:
            print("Forward pass output shape:", outputs.shape)

        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        if step % 5000 == 0:
            print(f"Step {step}: Loss = {loss.item():.4f}")

    print(f"Epoch {epoch+1} Average Loss: {running_loss / len(trainloader):.4f}")

print("\nTraining Completed Successfully.")


100%|██████████| 170M/170M [00:12<00:00, 13.3MB/s]


Dataset Loaded:
Total training samples: 50000
Batch size: 4
Image shape: torch.Size([3, 32, 32])

Sample batch - images tensor shape: torch.Size([4, 3, 32, 32])
Sample batch - labels: tensor([3, 2, 2, 5])

Model Architecture:
SimpleCNN(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

--- Starting Training ---

Epoch 1 ----------------------
Forward pass output shape: torch.Size([4, 10])
Step 0: Loss = 2.2690
Step 5000: Loss = 1.7494
Step 10000: Loss = 0.7603
Epoch 1 Average Loss: 1.7184

Epoch 2 ----------------------
Forward pass output shape: torch.Size([4, 10])
Step 0: Loss = 0.6488
Step 5000: Loss = 1.8990
Step 10000: Loss = 0.6801
Epoch 2 Averag